### ISSUE TITLE
Split config.yaml `phenotype_only` into gene and variant fields

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/pheval#164]
Currently the config.yaml has a `phenotype_only` field which is a weird Exomiser way of saying 'genes, but no variant analysis'. This is confusing, so it needs to be said more explicitly:

```yaml
variant_analysis: False
gene_analysis: True
disease_analysis: True
```
i.e. 'phenotype_only' is a weird amalgam of gene and variant...

However, this will break most of the existing runners, so do it pre 1.0.0 release, but not this instant!

_Originally posted by @julesjacobsen in https://github.com/monarch-initiative/pheval/pull/163#discussion_r1234219308_
