### ISSUE TITLE
Extend scramble phenopackets to read and write the corpus.yml file

### ISSUE THREAD

**Issue by souzadevinicius** [monarch-initiative/pheval#49]
Implement a function that reads the corpus.yml file.
This corpus will describe the experiments' characteristics.

As an example, a draft corpus.yml file might look like this:

```
  update_phenopacket_gene_identifier:
    update: Yes
    gene_identifier_to_update: ensembl_id
  create_spiked_vcf:
      spike: Yes
      path_to_template_vcf: /Users/yaseminbridges/Documents/GitHub/pheval/testdata/template_vcf/template_exome_hg19.vcf.gz
      path_to_template_vcf_directory:
```
